"""empty message

Revision ID: a469d341806b
Revises: 496ade514967
Create Date: 2022-11-12 11:02:57.539671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a469d341806b'
down_revision = '496ade514967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_people', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_planet', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('name', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_unique_constraint(None, 'user', ['last_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
